### ISSUE TITLE
About the Revolving Test

### ISSUE THREAD

**Issue by AlphaPlusTT** [fcjian/AeDet#15]
By changing the order of the images from ['FRONT LEFT', 'FRONT', 'FRONT RIGHT', 'BACK RIGHT', 'BACK', 'BACK LEFT'] to ['BACK LEFT', 'FRONT LEFT', 'FRONT', 'FRONT RIGHT', 'BACK RIGHT', 'BACK'], have the camera's intrinsic and extrinsic parameters been adjusted accordingly? Could you elaborate on the details of this experimental aspect?

**Comment by fcjian** [comment]
Hi, @AlphaPlusTT In revolving test, it is not necessary to modify the intrinsic parameters. Only the camera extrinsics need to be rotated clockwise by 60 degrees. Once the inference process is completed, the predicted bounding box should be rotated counterclockwise by 60 degrees before evaluation.

**Comment by AlphaPlusTT** [comment]
Thanks for the explanation, is this process similar to BEV's rotation data augmentation?

**Comment by fcjian** [comment]
Yes, it is similar to BEV's rotation data augmentation. The difference is that we rotate the predicted bounding boxes counterclockwise after inference, aligning them with the standard ground truth for evaluation.
