### ISSUE TITLE
great work! when will the code be released?

### ISSUE THREAD

**Issue by JsutCheng** [fcjian/AeDet#2]

**Comment by fcjian** [comment]
Thanks for your attention. We are currently organizing the code and plan to release it in April.

**Comment by JsutCheng** [comment]
Thanks for your reply, looking forward to seeing the code soon.

**Comment by JsutCheng** [comment]
Will the paper releated performance model all be released?

**Comment by JsutCheng** [comment]
resnet50(256 768) and resnet101(512x1408) hope two exps all to be released.

**Comment by fcjian** [comment]
We have uploaded the config files and checkpoints of the two experiments, please refer to [exps/adet](https://github.com/fcjian/AeDet/tree/main/exps/aedet).
