### ISSUE TITLE
visualization of bev feature

### ISSUE THREAD

**Issue by jianingwangind** [fcjian/AeDet#8]
Thanks for sharing the great work!

May i ask how you visualize the high-dimentional bev feature map?

**Comment by fcjian** [comment]
You can use matplotlib to visualize the high-dimentional bev feature map, for example:

`import matplotlib.pyplot as plt`
`feat_map = bev_feat[0].max(0)[0].numpy()`
`fig = plt.figure(figsize=(20, 20))`
`ax = fig.add_subplot(111)`
`im = ax.imshow(feat_map, cmap=plt.cm.jet)`
`plt.axis('off')`
`plt.show()`

**Comment by jianingwangind** [comment]
Thanks a lot
